# SPDX-FileCopyrightText: 2024 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0

[default]

[default.extend-words]
restat = "restat"

# thanks to base yamls
idae = "idae"

[files]
extend-exclude = ["serpent-style/**/*"]
