[package]
name = "astr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
diesel.workspace = true
stable_deref_trait = "1.2.1"
triomphe.workspace = true

[lints]
workspace = true
